// <auto-generated />
using System;
using FarmProject.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmProject.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220824214227_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FarmProject.Shared.Barn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Barn");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "porumb",
                            Quantity = 4
                        },
                        new
                        {
                            Id = 2,
                            Name = "fan",
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("FarmProject.Shared.Fowl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("Corn")
                        .HasColumnType("float");

                    b.Property<double?>("Hey")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fowls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Corn = 2.0,
                            Name = "gaini",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "gaste",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            Corn = 1.0,
                            Name = "rate",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "curci",
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("FarmProject.Shared.Quadruped", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("Corn")
                        .HasColumnType("float");

                    b.Property<double?>("Hey")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Quadrupeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Corn = 2.0,
                            Hey = 0.0,
                            Name = "porci",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "oi",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            Hey = 0.5,
                            Name = "bovine",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "cai",
                            Quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
